// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSB9-HObJR7NcMJStqE8UnT-4L6J7_tEw',
    appId: '1:805653977002:web:e3ff2f0b0ce5a93f15bdd3',
    messagingSenderId: '805653977002',
    projectId: 'sundayschoolmanual-e2951',
    authDomain: 'sundayschoolmanual-e2951.firebaseapp.com',
    storageBucket: 'sundayschoolmanual-e2951.firebasestorage.app',
    measurementId: 'G-JMYNSDFG0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6cW1knkuWzdozNjMjDzMkpDM7doA1XDI',
    appId: '1:805653977002:android:d45282739866d3c915bdd3',
    messagingSenderId: '805653977002',
    projectId: 'sundayschoolmanual-e2951',
    storageBucket: 'sundayschoolmanual-e2951.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtiUZtcefBrr_hQSB3QVMpDTdLc5dftbM',
    appId: '1:805653977002:ios:1a8de578e1074d5a15bdd3',
    messagingSenderId: '805653977002',
    projectId: 'sundayschoolmanual-e2951',
    storageBucket: 'sundayschoolmanual-e2951.firebasestorage.app',
    androidClientId: '805653977002-bek70iu4r5fau2pheasceq60jan5gvaf.apps.googleusercontent.com',
    iosClientId: '805653977002-o325l44gram6ig9vtiectqdj58tkkept.apps.googleusercontent.com',
    iosBundleId: 'com.ofcsoftwaredevops.rccgsundayschoolmanual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtiUZtcefBrr_hQSB3QVMpDTdLc5dftbM',
    appId: '1:805653977002:ios:ef4cba89053bbefa15bdd3',
    messagingSenderId: '805653977002',
    projectId: 'sundayschoolmanual-e2951',
    storageBucket: 'sundayschoolmanual-e2951.firebasestorage.app',
    iosBundleId: 'com.example.appDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSB9-HObJR7NcMJStqE8UnT-4L6J7_tEw',
    appId: '1:805653977002:web:43c4d994c7f8ebb915bdd3',
    messagingSenderId: '805653977002',
    projectId: 'sundayschoolmanual-e2951',
    authDomain: 'sundayschoolmanual-e2951.firebaseapp.com',
    storageBucket: 'sundayschoolmanual-e2951.firebasestorage.app',
    measurementId: 'G-7GKBP8LQ0S',
  );
}
